### PR TITLE
Robust makefile and workflow to build dev and production ASM and WASM versions

### PR DESCRIPTION
**Pull request by Jaifroid**
This is for updates to the workflow I created in #13.

### CODE REVIEW

**Comment by Jaifroid** [comment]
This workflow ran into the same issue as documented in https://github.com/openzim/javascript-libzim/issues/9#issuecomment-1321188045, i.e.:
```
wasm-ld: error: /src/build/lib/libzim.a: archive has no index; run ranlib to add one
wasm-ld: error: /src/build/lib/libzstd.a: archive has no index; run ranlib to add one 
```
You can see the error in the workflow log here: https://github.com/openzim/javascript-libzim/actions/runs/3535606139/jobs/5933803167#step:4:9482.

It's very strange that mossroy was able to compile this way, but I could not reproduce it, and now GitHub actions running on Ubuntu-latest cannot reproduce it either.

@mgautierfr Do you have any clue how to solve this error with `libzim.a` and `libzstd.a` not having indices? According to [the suggested solutions I found](https://github.com/openzim/javascript-libzim/issues/9#issuecomment-1321188045), it should be something very small, but I don't know where to add one of those commandline parameters.

**Comment by Jaifroid** [comment]
Success! Adding `ar = 'emar'` to [emscripten-crosscompile.ini](https://github.com/openzim/javascript-libzim/pull/14/commits/99dbe0e40a026f3b1036635d3028b0b4958c6ec2) [allows the build to succeed](https://github.com/openzim/javascript-libzim/actions/runs/3538418374).

I now need to add some steps to save the built files `a.out.js` and `a.out.wasm`. @kelson42, what would you recommend? Should the built files be pushed to `master` (they are on master), to a branch/PR, or added as an asset to a draft release (which would only be accessible to maintainers of this Repo)?

**Comment by Jaifroid** [comment]
For now, I've added steps to archive the artefacts under the action. You can see an example here (scroll to bottom of page, can be downloaded as a zipped archive):

https://github.com/openzim/javascript-libzim/actions/runs/3539162287

Next steps would be:

* Decide if this workflow should run automatically on push to master, or only be manually dispatched
* Decide if this workflow should update master with the newly built files, or create a PR to do so, or merely archive the artefacts as at present
* Create a similar workflow to run nightly, but using the `libzim.a` from kiwix-build (#12) and publishing to download.kiwix.org
* Decide which workflow should run when creating a release/tag and publishing `a.out.js` and `a.out.wasm` to download.kiwix.org/release

**Comment by Jaifroid** [comment]
@kelson42 I've asked for you to review this PR, but really it's the [whole workflow on this branch](https://github.com/openzim/javascript-libzim/blob/Create-workflow-to-build-WASM/.github/workflows/build_libzim_wasm.yml) I'd like advice on, and these points in particular:

* Is the workflow correctly named (Docker Inage CI)?
* Should it be run on push to master?
* What should I do with the build artefacts (they are currently archived under the workflow run)?

**Comment by kelson42** [comment]
@Jaifroid I will have a look this WE.

**Comment by kelson42** [comment]
> * s the workflow correctly named (Docker Inage CI)?

I prefer to just call it `CI`

> * Should it be run on push to master?

Usually I want to have in it in pull requests (for obvious reasons) and each time a commit happens on master (to be able to have an overall CI badge and know if `master` is OK. Like here
https://github.com/openzim/mwoffliner/blob/master/.github/workflows/ci.yml#L3

> * What should I do with the build artefacts (they are currently archived under the workflow run)?

We have different approaches over repositories, but I wonder if https://github.com/openzim/mwoffliner/blob/master/.github/workflows/ci.yml#L3 should not be the ultimate solution.

Hopefully I understand what you do properly. What I wonder here, is that all run in a Docker instance so this is pretty not transparent for me. Not sure we need that anymore. or even we should do that. On the top of it, it seems this Docker compiles everything, but here the binaries done by libzim CD should be used.

**Comment by Jaifroid** [comment]
> I prefer to just call it `CI`

That would be fine. I'm not sure if this should be the nightly CI, however, because this builds libzim from scratch, and doesn't use the output of kiwix-build (`libzim.a`). I think mgautierfr will complete that integration, if I've understood correctly.

> Usually I want to have in it in pull requests (for obvious reasons) and each time a commit happens on master (to be able to have an overall CI badge and know if `master` is OK. Like here https://github.com/openzim/mwoffliner/blob/master/.github/workflows/ci.yml#L3

So I guess it depends on the status of this workflow: I conceived it just as a tool to be run manually when a dev wants to build everything from scratch on-demand.

> We have different approaches over repositories, but I wonder if https://github.com/openzim/mwoffliner/blob/master/.github/workflows/ci.yml#L3 should not be the ultimate solution.

Thanks, I'll take a look at that.
 
> Hopefully I understand what you do properly. What I wonder here, is that all run in a Docker instance so this is pretty not transparent for me. Not sure we need that anymore. or even we should do that. On the top of it, it seems this Docker compiles everything, but here the binaries done by libzim CD should be used.

Emscripten provides Docker images for developers to run it in a consistent and controlled environment. It's convenient, but of course we could provide an Emscripten setup in a GitHub Ubuntu instance. Maybe @mgautierfr would prefer that we do it that way for a nightly CI that uses `libzim.a` from kiwix-build?

To be clear, the Docker container attaches the files from this Repo, and uses them to build the WASM, so it's not quite a black box, and it does provide full logging, as you can see from the [latest action run](https://github.com/openzim/javascript-libzim/actions/runs/3539162287/jobs/5940760100).

**Comment by Jaifroid** [comment]
Here's what I propose:

* This workflow builds the libzim WASM based on the latest ***released*** version of libzim and a known stable version of Emscripten (as provided in their Docker container). As such, it could be run when a tag is created, and it could upload its output to GitHub releases (also, potentially to download.kiwix.org/release/). It can also be run on-demand (workflow dispatch), in which case it would not upload its output, only archive it under the workflow. When we have tests, it would also run tests on what it has built.
* A different CI would be run nightly and on pull request / push to master. The nightly CI would take the latest ***nightly*** version of `libzim.a`, build the libzim WASM and the Web Worker, and then test them. It could also use the latest version of Emscripten, not a Docker container. If it's a nightly job (rather than push/PR), it would also upload its output to download.kiwix.org/nightly/.

Does this sound like a useful distinction? The main difference is that the input for the nightly CI would be the potentially unstable, nightly `libzim.a`, rather than the released version.

**Comment by kelson42** [comment]
> > I prefer to just call it `CI`
> 
> That would be fine. I'm not sure if this should be the nightly CI, however, because this builds libzim from scratch, and doesn't use the output of kiwix-build (`libzim.a`). I think mgautierfr will complete that integration, if I've understood correctly.

@mgautierfr might help to understand why you can not use the libzim release wasm code, but not to rebuild the recompile the libzim. This should not take here in this repo, at least for sure not in the CI. Duties of respective repositories should not be mixed.

The nightly build should not be part of the CI, but of the CD (this should be an other workflow). Here maybe something to read https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment

> > Usually I want to have in it in pull requests (for obvious reasons) and each time a commit happens on master (to be able to have an overall CI badge and know if `master` is OK. Like here https://github.com/openzim/mwoffliner/blob/master/.github/workflows/ci.yml#L3
> 
> So I guess it depends on the status of this workflow: I conceived it just as a tool to be run manually when a dev wants to build everything from scratch on-demand.

There seems to be a fundamental mix between this Docker image/container which was useful at some point but for which I see no usage anymore and what should be a CI. The CI is an automated process to secure no regression are introduced with new code. So here the CI of this repository should test the code of this repo. As such it is an automatic tool applied on relevant branches, typically feature branches or master.

> > We have different approaches over repositories, but I wonder if https://github.com/openzim/mwoffliner/blob/master/.github/workflows/ci.yml#L3 should not be the ultimate solution.
> 
> Thanks, I'll take a look at that.
> 
> > Hopefully I understand what you do properly. What I wonder here, is that all run in a Docker instance so this is pretty not transparent for me. Not sure we need that anymore. or even we should do that. On the top of it, it seems this Docker compiles everything, but here the binaries done by libzim CD should be used.
> 
Emscripten provides Docker images for developers to run it in a consistent and controlled environment. It's convenient, but of course we could provide an Emscripten setup in a GitHub Ubuntu instance. Maybe @mgautierfr would prefer that we do it that way for a nightly CI that uses `libzim.a` from kiwix-build?

This might be convenient, but that does not mean we should or have to use it for the CI and it does not mean either we should compile the libzim here. Yes, we insist that this is not the purpose of this repository to compile the lizim, but only the wrapper code.

> To be clear, the Docker container attaches the files from this Repo, and uses them to build the WASM, so it's not quite a black box, and it does provide full logging, as you can see from the [latest action run](https://github.com/openzim/javascript-libzim/actions/runs/3539162287/jobs/5940760100).

Yes, I understand, if this has to be done that way, why not.... but pleast don't compile the libzim here.

**Comment by kelson42** [comment]
Sorry, if there is a kind of redundancy with my previous comment.

>     * This workflow builds the libzim WASM based on the latest _**released**_ version of libzim and a known stable version of Emscripten (as provided in their Docker container). As such, it could be run when a tag is created, and it could upload its output to GitHub releases (also, potentially to download.kiwix.org/release/). It can also be run on-demand (workflow dispatch), in which case it would not upload its output, only archive it under the workflow. When we have tests, it would also run tests on what it has built.

OK. Usually our **CD workflows** deploy source code to Github releases and download.kiwix.org/releases, but push the binary builds (here wasm) to download.kiwix.org/releases. I think this is still the right approach.

>     * A different CI would be run nightly and on pull request / push to master. The nightly CI would take the latest _**nightly**_ version of `libzim.a`, build the libzim WASM and the Web Worker, and then test them. It could also use the latest version of Emscripten, not a Docker container. If it's a nightly job (rather than push/PR), it would also upload its output to download.kiwix.org/nightly/.

Yes, this is how it works usually. You have to understand that by doing so, you will have to pretty quickly implement libzim changes in the wrapper. I recommend otherwise to use a fix/stable versions of dependences and compilation tools.

> Does this sound like a useful distinction? The main difference is that the input for the nightly CI would be the potentially unstable, nightly `libzim.a`, rather than the released version.

From a high level, yes.

**Comment by Jaifroid** [comment]
OK, thanks for the useful insights, @kelson42. I'm very new to CI and CD. And I'm very happy not to build libzim here once we have public, released versions of `libzim.a` as well as nightly versions that the scripts here can work off.

**Comment by Jaifroid** [comment]
@kelson42 I'm about to add code to the workflow that will upload the zipped WASM and ASM files, including wrappers, to master.download.kiwix.org. These would be "release" versions (stable) rather than nightly, as discussed above. Could I ask you to decide the following?

* Where should these released files be uploaded? They are "drivers" rather than complete working applications. They will be released in GitHub releases -- [see automatically created draft release here](https://github.com/openzim/javascript-libzim/releases/tag/untagged-039b32be90df8471a68a) -- but I need to know where to put them on download.kiwix.org.
* I don't have access to this Repos Settings / Secrets -- I need to add the secret to access master.download.kiwix.org in GH Actions. Could you either give me enough access rights, or else tell me the name of the secrets (if they have been added as org secrets)?
* What file format should I use? There is no "architecture", but I guess we could consider `asm` and `wasm` as pseudo-architectures, so I would simply propose:
  +  `libzim_wasm_0.0.0.zip`
  + `libzim_asm_0.0.0.zip`

Many thanks.

**Comment by kelson42** [comment]
I would really prefer to push releases based on libzim of http://download.openzim.org/release/libzim. Fixing https://github.com/openzim/javascript-libzim/issues/8 should be the priority, @mgautierfr What do you think?

Otherwise it should be published in https://download.openzim.org/release/javascript-libzim IMO.

Format of your release files looks good IMO, @rgaudin ?

@rgaudin Could you please push here the necessary secrets so we can upload to https://download.openzim.org/release/javascript-libzim from this repo?

**Comment by Jaifroid** [comment]
> I would really prefer to push releases based on libzim of http://download.openzim.org/release/libzim. Fixing #8 should be the priority, @mgautierfr What do you think?

@kelson42 The logic of this workflow is such that it will be easy to plug in the `libzim.a` and its dependencies once we have working versions. They are currently failing -- see my report in https://github.com/kiwix/kiwix-build/issues/552#issuecomment-1334691832. I don't know how to fix that on the kiwix-build side. This workflow has the capacity to build everything from scratch (a capacity we should retain, so as not to lose the know-how for doing it with Emscripten), but it will be easy to make it use pre-built binaries instead, or to provide a workflow dispatch option to use either for testing, defaulting to prebuilt. 

> Otherwise, it should be published in https://download.openzim.org/release/javascript-libzim IMO.

OK, thanks. Until #12 / https://github.com/kiwix/kiwix-build/issues/552 can be fixed, I'd like to publish a version 0.0.1 that I could use for https://github.com/kiwix/kiwix-js/pull/935 (which is working well). It's a major advance.

> Format of your release files looks good IMO, @rgaudin ?
> 
> @rgaudin Could you please push here the necessary secrets so we can upload to https://download.openzim.org/release/javascript-libzim from this repo?

**Comment by Jaifroid** [comment]
@kelson42 This is ready to merge. To summarize what it does, and what I undertake to do when #12 / https://github.com/kiwix/kiwix-build/issues/552 are fixed with working binaries:

* It fixes the Makefile that dattaz, mossroy and @mgautierfr created (which compiles the WASM / ASM files and JS wrapper) so that it is useable in GitHub Actions:
  + Please note that no matter HOW we build the binaries (`libzim.a`) and all the dependencies, this Makefile will need to run in order to compile the final WASM;
* This PR adds a workflow and accompanying bash script that compiles the WASM / ASM artefacts on:
  + Push to master;
  + Pull request;
  + On creation of a tag matching 'v...';
  + With a workflow dispatch;
* If triggered by a PR or push to master, the artefacts are merely archived under the workflow run (Actions tab) and no further action is taken - this serves a CI function;
* If it is a new matching tag, or a workflow dispatched with a version matching 'v[0-9.]+':
  + A DRAFT release is created;
  + The artefacts are zipped with versioned filenames as agreed above, and added to the draft release;
* Once the draft release is published, then a separate workflow (not in this PR, see #20) will upload the artefacts from the GitHub release to `openzim/release/javascript-libzim`;
* Additionally, this PR gives more consistent and comprehensible names to a number of needed source files in the repo and to the output files.

**IMPORTANT observations:**

* I ***undertake*** to alter the Makefile to pull the binaries from the latest openzim release of them as soon as we have working versions of `libzim.a` and its dependencies. This will be easy, because the Makefile has been built in such a way as to skip building the binaries if they already exist in the file system;
* Any releases I make using the unaltered Makefile (i.e. built from scratch) will be marked as "Prerelease" and will be numbered `v0.x.x`;
* The reason for my wanting to have a prerelease version I can use in Kiwix JS and Kiwix JS Windows now, is because I have already successfully integrated libzim-based full-text search into the codebase, and this would be a major advance for these apps, and a first (hopefully of many) tangible success of this project;
* I have tested the workflow as much as I can, and it is passing, but to test the full integration, I now need to merge.

Is this acceptable and may I merge? Needless to say, I've put a LOT of unplanned work into this. I'm motivated to do so because it will have such important benefits for the JavaScript apps.

**Comment by kelson42** [comment]
@Jaifroid This PR should not include compiled files, but this is the case.

**Comment by Jaifroid** [comment]
@kelson42 I can remove that. It will then pull the needed file from the URL you gave me. This is already in the Makefile.

**Comment by Jaifroid** [comment]
PS I meant "remove those", including the compiled files.

**Comment by kelson42** [comment]
@Jaifroid This is also important these files are removed from the git revision log, otherwise we will keep them in the clones forever.

**Comment by Jaifroid** [comment]
> @Jaifroid This is also important these files are removed from the git revision log, otherwise we will keep them in the clones forever.

OK, but please note that the compiled files `a.out.js` are already in the repo and have been there for a long time. All this does is rename them and update them. I can delete them in this PR, so they'll disappear on squash / rebased, but it's probably much harder to remove the original compiled versions from the Git log of this Repo!

**Comment by Jaifroid** [comment]
@kelson42 One slight difficult is that if I remove ALL of the compiled binaries, the live demo will stop working, and we currently use this for manual testing (it is published on GitHub pages). Should I move the demo's dependencies into a separate directory? The dependency will be one `libzim-wasm.js` and one `libzim-wasm.wasm`.

**Comment by kelson42** [comment]
@Jaifroid Either things (binaries, compiled coded, computer generated content) are compiled or they are downloaded, but the git is not the right place for them.

**Comment by Jaifroid** [comment]
@kelson42 I think removing the [live demo](https://openzim.github.io/javascript-libzim/) is outside the scope of this PR and needs further discussion (I know @mgautierfr uses it, for example). Here's what I suggest:

* I make an issue to discuss what to do with it and how to keep it running if needed;
* In this PR I move the needed files into a `tests` directory (including demo itself);
* I remove the compiled binaries that the demo doesn't need, leaving only the JS wrapper and the WASM (in the tests directory) needed to run the demo.

Is this OK?

**Comment by Jaifroid** [comment]
All tasks mentioned in https://github.com/openzim/javascript-libzim/pull/14#issuecomment-1336490397 are completed and everything is compiling successfully.

**Comment by Jaifroid** [comment]
I am going to release an updated WikiMed using libzim for full text search. To do so, I need to be able to point to the source code for the libzim release, and to do this, I need to merge this PR and create a v0.0.2 pre-release with a tag that won't disappear when this branch is squashed.

Merging this PR also means I can pretty quickly #12 to start using the kiwix-build binaries as source for compiling the WASM and ASM versions.

So, unless I hear to the contrary, I'll merge this PR later today, Thursday (afternoon).

**Pull request merged**
