### PR TITLE
Update libzim 8.2.1 for release 0.3

### LINKED ISSUE #55: Update release for source build of libzim v8.2.1
I understand that v8.2.1 of libzim has been released, so we should evaluate and release a corresponding WASM version if all is OK.

### PR DESCRIPTION
**Pull request by Jaifroid**
Closes #55.

### CODE REVIEW

**Comment by Jaifroid** [comment]
@mgautierfr At long last, I'm updating the source for the javascript-libzim build to v8.2.1 of libzim. However, in the build log, I notice a bunch of deprecation warnings related to code in the bindings, starting [here](https://github.com/openzim/javascript-libzim/actions/runs/6492006369/job/17630199767?pr=56#step:4:107). Is this something I should be worried about? It looks like the bindings are depending on methods that have been marked for deprecation (I assume in libzim itself). If this is the case, then we could be looking at the build breaking once those methods disappear. Are there simple alternatives we can substitute?

**Comment by Jaifroid** [comment]
I've tested the wasm release artefact from this PR in https://github.com/kiwix/kiwix-js/pull/766, and all seems to be working fine.

**Comment by Jaifroid** [comment]
Also builds correctly from source (without using libzim WASM binary, but building it from scratch) after updating zlib to v1.3.

**Comment by mgautierfr** [comment]
> I notice a bunch of deprecation warnings related to code in the bindings, starting [here](https://github.com/openzim/javascript-libzim/actions/runs/6492006369/job/17630199767?pr=56#step:4:107). Is this something I should be worried about?

They are warning about libzim using cpp features which are deprecated in c++17.
Next release of libzim will have them fixed (it is already on master).
Nothing to worry about and nothing to do on your side (maybe compile in c++11)

**Comment by Jaifroid** [comment]
OK, thanks for the reassurance @mgautierfr!

**Comment by Jaifroid** [comment]
Confirmed that wasm build from source (without libzim.a) works fine too. So this is ready to merge, and I can prepare the new release.

**Pull request merged**
